name: Auto PR Comment

on:
  pull_request:
    types: [opened]

permissions:
  contents: read
  pull-requests: write  # Ensure token has permission to update PR

jobs:
  update-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Ticket Number from Branch Name
        id: extract_ticket
        run: |
         BRANCH_NAME="${{ github.head_ref }}"
         BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's/feature\///g; s/hotfix\///g')
         TICKET_NUMBER=""
         if [[ "$BRANCH_NAME" =~ ^[0-9]+-[^/]+$ ]]; then
          echo "Branch name matches the pattern number-XXX"
          TICKET_NUMBER=$(echo "$BRANCH_NAME" | grep -oE '^[0-9]+')
          echo "Ticket Number: $TICKET_NUMBER"
          else
          echo "Branch name does not match the pattern number-XXX"
          echo "Ticket Number: $TICKET_NUMBER"
          fi
          echo "TICKET_NUMBER=$TICKET_NUMBER" >> $GITHUB_ENV
      - name: Update PR Description
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ticketNumber = process.env.TICKET_NUMBER;
            if (ticketNumber) {
              const pr = context.payload.pull_request;
              github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                body: `## Task: #${ticketNumber}\n\n https://dev.azure.com/fadv-devops/ProdDev/_workitems/edit/${ticketNumber}\n\n ${pr.body}`
              });
            }
