name: Auto PR Comment

on:
  pull_request:
    types: [opened]

permissions:
  contents: read
  pull-requests: write  # Ensure token has permission to update PR

jobs:
  update-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Ticket Number from Branch Name
        id: extract_ticket
        run: |
         BRANCH_NAME="${{ github.head_ref }}"
         TICKET_NUMBER="0"
         if [[ "$BRANCH_NAME" =~ ^[0-9]+-[a-zA-Z0-9]+$ ]]; then
          TICKET_NUMBER=$(echo "$BRANCH_NAME" | grep -oE '^[0-9]+')
         fi

      - name: Update PR Description
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ticketNumber = process.env.TICKET_NUMBER;
            if (ticketNumber && ticketNumber != "0") {
              const pr = context.payload.pull_request;
              github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                body: `## Task: #${ticketNumber}\n\n${pr.body || `https://dev.azure.com/fadv-devops/ProdDev/_workitems/edit/${ticketNumber}`}`
              });
            }
